services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      - BACKEND_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: lunch-app-nginx
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: lunch-app-db
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/0000_init_up.sql:/0000_init_up.sql
  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      ADMINER_DESIGN: nette
    depends_on:
      - db

volumes:
  pgdata: