services:
  nginx:
    image: ghcr.io/m368c/gimvic-lunch-app/nginx:latest
    environment:
      - BACKEND_HOST=backend
    container_name: lunch-app-nginx
    restart: always
    ports:
      - "127.0.0.1:8888:80"
    depends_on:
      - db
      - backend
  backend:
    image: ghcr.io/m368c/gimvic-lunch-app/backend:latest
    container_name: lunch-app-backend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: lunch-app-db
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/0000_init_up.sql:/0000_init_up.sql

volumes:
  pgdata: