services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: lunch-app-backend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DATABASE_URL
      - SMTP_USERNAME
      - SMTP_KEY
      - FROM_EMAIL
      - REPLY_TO_EMAIL
      - TO_EMAIL
    depends_on:
      - db
    profiles:
      - backend
  db:
    image: postgres:17
    container_name: lunch-app-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/0000_init_up.sql:/0000_init_up.sql
  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      ADMINER_DESIGN: nette
    depends_on:
      - db

volumes:
  pgdata: